### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by jgordijn** [lightbend-training/course-management-tools#1]
I'm trying this out, but I cannot get the project to compile. The dependency to org.scala-sbt %% io % "0.13.12" cannot be found.

I have a plain sbt setup without extra repos. I use coursier (but also tried without coursier)

```
coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
  org.scala-sbt:io_2.11:0.13.12:
    not found:
      /Users/jgordijn/.ivy2/local/org.scala-sbt/io_2.11/0.13.12/ivys/ivy.xml
      https://repo1.maven.org/maven2/org/scala-sbt/io_2.11/0.13.12/io_2.11-0.13.12.pom
      http://repo.typesafe.com/typesafe/releases/org/scala-sbt/io_2.11/0.13.12/io_2.11-0.13.12.pom
[error] (*:coursierResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]   org.scala-sbt:io_2.11:0.13.12:
[error]     not found:
[error]       /Users/jgordijn/.ivy2/local/org.scala-sbt/io_2.11/0.13.12/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/org/scala-sbt/io_2.11/0.13.12/io_2.11-0.13.12.pom
[error]       http://repo.typesafe.com/typesafe/releases/org/scala-sbt/io_2.11/0.13.12/io_2.11-0.13.12.pom
[error] Total time: 2 s, completed Nov 4, 2016 2:34:22 PM
```

**Comment by eloots** [comment]
Hi Jeroen, which course & version is this? Is this on the student repo or the teacher repo for that course?

**Comment by jgordijn** [comment]
Hi Eric, 

It is not in a course, but in this repo. I cannot compile the `course-management-tools`.

**Comment by eloots** [comment]
Hi Jeroen,

I’ve actually heard this happening to one of my colleagues too. Not sure what the problem was though. I do remember that he was able to run the app from the sbt prompt though (weirdly enough…). Guess I need to look at this in more detail.

Compilation does work in my case though… so I can’t reproduce it…

[ericloots@Eric-Loots-MBP] $ sbt
[info] Loading global plugins from /Users/ericloots/.sbt/0.13/plugins
[info] Loading project definition from /Users/ericloots/Trainingen/LightbendTraining/Studentify/course-management-tools/project/project
[info] Loading project definition from /Users/ericloots/Trainingen/LightbendTraining/Studentify/course-management-tools/project
[info] Set current project to studentify (in build file:/Users/ericloots/Trainingen/LightbendTraining/Studentify/course-management-tools/)
> clean
[success] Total time: 0 s, completed 4-nov-2016 16:45:07
> compile
[info] Updating {file:/Users/ericloots/Trainingen/LightbendTraining/Studentify/course-management-tools/}course-management-tools...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 10 Scala sources to /Users/ericloots/Trainingen/LightbendTraining/Studentify/course-management-tools/target/scala-2.11/classes...
[success] Total time: 5 s, completed 4-nov-2016 16:45:14
>

project/build.properties selects sbt 0.13.11. You can bump it to 0.13.13. In any case, doesn’t explain why it works in my case and not yours. Do give 0.13.13 a try though…

Eric

**Comment by eloots** [comment]
Jeroen, I just added an explicit resolver for the Typesafe Ivy-releases to the build definition. Hope this solves the issue. If not, we have to dig deeper. Keep me posted if this fixes the problem on your system

**Comment by eloots** [comment]
Jeroen, I've added a resolver for the Typesafe ivy-releases. Can you please try again and let me know if the problem is solved?

**Comment by eloots** [comment]
Hi Jeroen,

Wanted to ask if you re-tested with the latest version. I added a note to the issue, not sure you had a chance to read it.

Please let me know the status so that I can close the issue when so.

Cheers, Eric

**Comment by jgordijn** [comment]
Hi Eric,

Unfortunately it did not resolve the issue. See below. It is looking for the artifact in:
[http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/io_2.11/0.13.12/io_2.11-0.13.12.pom](http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/io_2.11/0.13.12/io_2.11-0.13.12.pom)

However I can find some data at (note org.scala-sbt vs org/scala-sbt):
[http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io_2.11/0.13.12/](http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io_2.11/0.13.12/)

```
[info] Updating course-management-tools
[trace] Stack trace suppressed: run last *:coursierResolution for the full output.
[error] (*:coursierResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]   org.scala-sbt:io_2.11:0.13.12:
[error]     not found:
[error]       /Users/jgordijn/.ivy2/local/org.scala-sbt/io_2.11/0.13.12/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/org/scala-sbt/io_2.11/0.13.12/io_2.11-0.13.12.pom
[error]       http://repo.typesafe.com/typesafe/releases/org/scala-sbt/io_2.11/0.13.12/io_2.11-0.13.12.pom
[error]       http://repo.typesafe.com/typesafe/ivy-releases/org/scala-sbt/io_2.11/0.13.12/io_2.11-0.13.12.pom
[error] Total time: 3 s, completed Nov 8, 2016 9:41:27 AM
```

**Comment by eloots** [comment]
Hi Jeroen,

New attempt. This change fixed the problem for one of my colleagues.

When blowing away the (ivy2) cached folders, the dependency is downloaded from the following location:

downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.11/jars/io.jar

Can you please give this one a try? Sorry for the confusion, but for some reason, I can’t reproduce the original problem…

Cheers, Eric

**Comment by jgordijn** [comment]
yes! Success! Thanks

**Comment by eloots** [comment]
Great; and a relief as I didn’t really have a handle on how to simulate this… Thanks for your patience!
