### ISSUE TITLE
Man color issue

### ISSUE THREAD

**Issue by WadeWaldron** [lightbend-training/course-management-tools#17]
An issue was originally reported in FTTAS: https://github.com/typesafe-training/fast-track-akka-scala/issues/17

Suggests that the colour scheme may not be appropriate in some cases. We should check if this is a problem with Studentify and try to remedy it if possible.

**Comment by eloots** [comment]
The issue is a studentify issue: we could easily change the default colours.
I will create a PR to change all utilisation of CONSOLE.BLUE to CONSOLE.GREEN. I showed the modified colour setup to students in one class and they were either neutral of in favour of the new colour.
Never had anyone complain about the utilisation of CONSOLE.RED

**Comment by WadeWaldron** [comment]
I am not sure about RED. The original issue certainly calls it out. Having said that, looking on my screen RED looks pretty good. Though if presenting on a crappy projector or screen, maybe it doesn't.

Is there perhaps a different shade of red that might be better?

**Comment by eloots** [comment]
Removed all utilisation of the colour Blue (`Console.BLUE`) for colouring output to the console in sbt. Implemented in PR #38
