### ISSUE TITLE
IntelliJ SBT Shell Support

### ISSUE THREAD

**Issue by patrick-premont** [lightbend-training/course-management-tools#48]
I usually use IntelliJ to present exercises in a course delivery. The new version 2017.2 includes an “SBT shell” with a nice visual completion feature.

However it does not play nice with our sbt tasks: 

* Typing man e is challenging. My workaround was to add a space after the e.
* None of our tasks, such as nextExercise are offered in completion.

I don’t know if there is something we can do to address these issues, but it would be nice.

**Comment by eloots** [comment]
I have used the sbt shell only a few times and even though and has been helpful in the Akka courses (for students who run on Windows), I still prefer a terminal with sbt.
That being said, I've just tried what you explain above, and indeed it's annoying that command such as `nextExercise` and `pullSolution` don't autocomplete when hitting the TAB key. Also, `man e` is tricky because it insist on making suggestions and the only way out is indeed to add a space after the 'e'.
In my opinion, we shouldn't spent time on trying to figure out how this can be fixed. Probably the best thing we can do is to open a ticket @ jetBrains...

**Comment by patrick-premont** [comment]
I noticed our tasks aren't showing up in `sbt tasks` or `sbt tasks -v` either. Maybe that's what completion is based on ?

**Comment by eloots** [comment]
Yes, but, when using a terminal and an sbt session, auto completion works and `tasks` doesn't show the commands either... so that doesn't distinguish it from what we see re `sbt tasks` in the IntelliJ sbt console...

**Comment by patrick-premont** [comment]
`nextExercise` and such are commands, not tasks. They are properly listed under `sbt commands`.
 
This appears to be a known limitation of IntelliJ's SBT Shell: https://youtrack.jetbrains.com/issue/SCL-11311
